version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees: []
    reviewers: []
    labels:
      - "dependencies"
    # Optionally ignore major version updates for specific packages
    # ignore:
    #   - dependency-name: "express"
    #     update-types: ["version-update:semver-major"]
